decimal-to-binary : decimal-to-binary.o
	g++ -o decimal-to-binary decimal-to-binary.o
decimal-to-binary.o : decimal-to-binary.cc
	g++ -c decimal-to-binary.cc
.PHONY:

clean:
	rm decimal-to-binary
	rm decimal-to-binary.o
